# -*- coding: utf-8 -*-
"""try_except.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K_0FeHrtxTY8xyx51xQQAxoXIghPH0Uq
"""

x = 7
try:  # Kodu dener ve hata varsa except bloğuna geçer, hata yoksa sadece try bloğu çalışır
  print(x)
  print(x / 0)

except NameError: # Tanımsız bir değişken yazdırdığımızda alırız
  print("X değişkenini tanımlamayı unuttunuz.")

except ZeroDivisionError: # 0'a bölme hatası
  print("Bölme işleminde payda 0 olamaz!")

# Kullanıcıdan istenilen değeri girmediği sürece programı sonlandırmaması için yazılmış kod

while True: # Sonsuz döngü için kullanılır
  try:
    sayi = int(input("Bir sayı girin: "))
    print(sayi + 5)
    break # Döngüyü kır
  except ValueError:
    print("Lütfen bir tam sayı girin!")

# Okuma modunda veri.txt dosyasını aç
# r: okuma, w: yazma, a: ekle

try:
  with open("veri.txt", "r") as dosya:
    dosya.read()

# Eğer daha önce veri.txt adında oluşturulmuş bir dosya varsa üzerine yazar, try except ile bunu ayırt edebiliriz
except FileNotFoundError: # Dosya bulunamadıysa dosyayı oluştur
  with open("veri.txt", "w") as dosya:
    pass

"""**Gezilebilirler** Iteratables"""

hayvanlar = ["Goril", "Aslan", "Kaplan", "Panter", "Kertenkele"]
#print(len(hayvanlar))

gezici = iter(hayvanlar)
# her bir yazışımızda bir sonraki elemanı verir next() ile

# uzun yol
#--------------
# print(next(gezici))
# print(next(gezici))
# print(next(gezici))
# print(next(gezici))
# print(next(gezici))

# kısa yol
#------------
i = 1
while i <= 5:
  print(next(gezici))
  i += 1

"""**Zaman Kütüphanesi**"""

from datetime import datetime, timedelta
# print(datetime.now()) # şu anki zamanı yazdırır
# print(datetime.today()) # now() ile aynı işlevdedir

suan = datetime.now()
print(suan.year) # sadece yılı yazdırır, istediğimiz kısmı almak için adını yazmamız yeterli
                 # day, month, year, hour, minute, second, microsecond

# Yazılan kodun ne kadar sürede işlendiğini gösterir
basla = datetime.now()
for i in range(int(1)):
  print("Merhaba!")

bitis = datetime.now()
print("Toplam Süre: ", (bitis-basla).total_seconds()) # total_seconds: toplam saniye

# timedelta: ne zamana kadar süreceğini belirler

odunc_tarihi = datetime.now()
teslim_tarihi = odunc_tarihi + timedelta(days=10) # ödünç tarihinin 10 gün sonrasını yazdırdık
print("Geri Alınacak Tarih: ", teslim_tarihi)

# %A = Gün, %B = Ay, %Y = Yıl
# Diğerlerini görmek için internetten strftime() parametrelerine bakabiliriz
print(teslim_tarihi.strftime("%d %B %Y")) # 21 Mart 2024

# 6 Mayıs 1976 Saat 04.30
# Yaş Hesaplama
dogum_gunu = datetime(1976, 5, 6, 4, 30)
yas = datetime.now() - dogum_gunu
print((yas // 365).days) # Yaşını verir, 47